/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/ui/button/Button.vue')['default']
    ColorModeButton: typeof import('./../src/components/buttons/ColorModeButton.vue')['default']
    IMaterialSymbolsLanguage: typeof import('~icons/material-symbols/language')['default']
    LocaleButton: typeof import('./../src/components/buttons/LocaleButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./../src/components/TheFooter.vue')['default']
  }
}
